import 'package:turbo_disc_golf/models/country.dart';

/// All countries in ISO 3166-1 alpha-2 format with flag emojis
/// Disc golf popular countries are listed first for better UX
const List<Country> allCountries = [
  // Popular disc golf countries
  Country(code: 'US', name: 'United States', flagEmoji: '🇺🇸'),
  Country(code: 'CA', name: 'Canada', flagEmoji: '🇨🇦'),
  Country(code: 'FI', name: 'Finland', flagEmoji: '🇫🇮'),
  Country(code: 'SE', name: 'Sweden', flagEmoji: '🇸🇪'),
  Country(code: 'NO', name: 'Norway', flagEmoji: '🇳🇴'),
  Country(code: 'GB', name: 'United Kingdom', flagEmoji: '🇬🇧'),
  Country(code: 'DE', name: 'Germany', flagEmoji: '🇩🇪'),
  Country(code: 'NL', name: 'Netherlands', flagEmoji: '🇳🇱'),
  Country(code: 'AU', name: 'Australia', flagEmoji: '🇦🇺'),
  Country(code: 'JP', name: 'Japan', flagEmoji: '🇯🇵'),

  // Rest of world (alphabetically)
  Country(code: 'AD', name: 'Andorra', flagEmoji: '🇦🇩'),
  Country(code: 'AE', name: 'United Arab Emirates', flagEmoji: '🇦🇪'),
  Country(code: 'AF', name: 'Afghanistan', flagEmoji: '🇦🇫'),
  Country(code: 'AG', name: 'Antigua and Barbuda', flagEmoji: '🇦🇬'),
  Country(code: 'AI', name: 'Anguilla', flagEmoji: '🇦🇮'),
  Country(code: 'AL', name: 'Albania', flagEmoji: '🇦🇱'),
  Country(code: 'AM', name: 'Armenia', flagEmoji: '🇦🇲'),
  Country(code: 'AO', name: 'Angola', flagEmoji: '🇦🇴'),
  Country(code: 'AQ', name: 'Antarctica', flagEmoji: '🇦🇶'),
  Country(code: 'AR', name: 'Argentina', flagEmoji: '🇦🇷'),
  Country(code: 'AS', name: 'American Samoa', flagEmoji: '🇦🇸'),
  Country(code: 'AT', name: 'Austria', flagEmoji: '🇦🇹'),
  Country(code: 'AW', name: 'Aruba', flagEmoji: '🇦🇼'),
  Country(code: 'AX', name: 'Åland Islands', flagEmoji: '🇦🇽'),
  Country(code: 'AZ', name: 'Azerbaijan', flagEmoji: '🇦🇿'),
  Country(code: 'BA', name: 'Bosnia and Herzegovina', flagEmoji: '🇧🇦'),
  Country(code: 'BB', name: 'Barbados', flagEmoji: '🇧🇧'),
  Country(code: 'BD', name: 'Bangladesh', flagEmoji: '🇧🇩'),
  Country(code: 'BE', name: 'Belgium', flagEmoji: '🇧🇪'),
  Country(code: 'BF', name: 'Burkina Faso', flagEmoji: '🇧🇫'),
  Country(code: 'BG', name: 'Bulgaria', flagEmoji: '🇧🇬'),
  Country(code: 'BH', name: 'Bahrain', flagEmoji: '🇧🇭'),
  Country(code: 'BI', name: 'Burundi', flagEmoji: '🇧🇮'),
  Country(code: 'BJ', name: 'Benin', flagEmoji: '🇧🇯'),
  Country(code: 'BL', name: 'Saint Barthélemy', flagEmoji: '🇧🇱'),
  Country(code: 'BM', name: 'Bermuda', flagEmoji: '🇧🇲'),
  Country(code: 'BN', name: 'Brunei', flagEmoji: '🇧🇳'),
  Country(code: 'BO', name: 'Bolivia', flagEmoji: '🇧🇴'),
  Country(code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flagEmoji: '🇧🇶'),
  Country(code: 'BR', name: 'Brazil', flagEmoji: '🇧🇷'),
  Country(code: 'BS', name: 'Bahamas', flagEmoji: '🇧🇸'),
  Country(code: 'BT', name: 'Bhutan', flagEmoji: '🇧🇹'),
  Country(code: 'BV', name: 'Bouvet Island', flagEmoji: '🇧🇻'),
  Country(code: 'BW', name: 'Botswana', flagEmoji: '🇧🇼'),
  Country(code: 'BY', name: 'Belarus', flagEmoji: '🇧🇾'),
  Country(code: 'BZ', name: 'Belize', flagEmoji: '🇧🇿'),
  Country(code: 'CC', name: 'Cocos (Keeling) Islands', flagEmoji: '🇨🇨'),
  Country(code: 'CD', name: 'Democratic Republic of the Congo', flagEmoji: '🇨🇩'),
  Country(code: 'CF', name: 'Central African Republic', flagEmoji: '🇨🇫'),
  Country(code: 'CG', name: 'Congo', flagEmoji: '🇨🇬'),
  Country(code: 'CH', name: 'Switzerland', flagEmoji: '🇨🇭'),
  Country(code: 'CI', name: 'Côte d\'Ivoire', flagEmoji: '🇨🇮'),
  Country(code: 'CK', name: 'Cook Islands', flagEmoji: '🇨🇰'),
  Country(code: 'CL', name: 'Chile', flagEmoji: '🇨🇱'),
  Country(code: 'CM', name: 'Cameroon', flagEmoji: '🇨🇲'),
  Country(code: 'CN', name: 'China', flagEmoji: '🇨🇳'),
  Country(code: 'CO', name: 'Colombia', flagEmoji: '🇨🇴'),
  Country(code: 'CR', name: 'Costa Rica', flagEmoji: '🇨🇷'),
  Country(code: 'CU', name: 'Cuba', flagEmoji: '🇨🇺'),
  Country(code: 'CV', name: 'Cabo Verde', flagEmoji: '🇨🇻'),
  Country(code: 'CW', name: 'Curaçao', flagEmoji: '🇨🇼'),
  Country(code: 'CX', name: 'Christmas Island', flagEmoji: '🇨🇽'),
  Country(code: 'CY', name: 'Cyprus', flagEmoji: '🇨🇾'),
  Country(code: 'CZ', name: 'Czechia', flagEmoji: '🇨🇿'),
  Country(code: 'DJ', name: 'Djibouti', flagEmoji: '🇩🇯'),
  Country(code: 'DK', name: 'Denmark', flagEmoji: '🇩🇰'),
  Country(code: 'DM', name: 'Dominica', flagEmoji: '🇩🇲'),
  Country(code: 'DO', name: 'Dominican Republic', flagEmoji: '🇩🇴'),
  Country(code: 'DZ', name: 'Algeria', flagEmoji: '🇩🇿'),
  Country(code: 'EC', name: 'Ecuador', flagEmoji: '🇪🇨'),
  Country(code: 'EE', name: 'Estonia', flagEmoji: '🇪🇪'),
  Country(code: 'EG', name: 'Egypt', flagEmoji: '🇪🇬'),
  Country(code: 'EH', name: 'Western Sahara', flagEmoji: '🇪🇭'),
  Country(code: 'ER', name: 'Eritrea', flagEmoji: '🇪🇷'),
  Country(code: 'ES', name: 'Spain', flagEmoji: '🇪🇸'),
  Country(code: 'ET', name: 'Ethiopia', flagEmoji: '🇪🇹'),
  Country(code: 'FR', name: 'France', flagEmoji: '🇫🇷'),
  Country(code: 'FO', name: 'Faroe Islands', flagEmoji: '🇫🇴'),
  Country(code: 'FK', name: 'Falkland Islands', flagEmoji: '🇫🇰'),
  Country(code: 'FM', name: 'Micronesia', flagEmoji: '🇫🇲'),
  Country(code: 'GA', name: 'Gabon', flagEmoji: '🇬🇦'),
  Country(code: 'GD', name: 'Grenada', flagEmoji: '🇬🇩'),
  Country(code: 'GE', name: 'Georgia', flagEmoji: '🇬🇪'),
  Country(code: 'GF', name: 'French Guiana', flagEmoji: '🇬🇫'),
  Country(code: 'GG', name: 'Guernsey', flagEmoji: '🇬🇬'),
  Country(code: 'GH', name: 'Ghana', flagEmoji: '🇬🇭'),
  Country(code: 'GI', name: 'Gibraltar', flagEmoji: '🇬🇮'),
  Country(code: 'GL', name: 'Greenland', flagEmoji: '🇬🇱'),
  Country(code: 'GM', name: 'Gambia', flagEmoji: '🇬🇲'),
  Country(code: 'GN', name: 'Guinea', flagEmoji: '🇬🇳'),
  Country(code: 'GP', name: 'Guadeloupe', flagEmoji: '🇬🇵'),
  Country(code: 'GQ', name: 'Equatorial Guinea', flagEmoji: '🇬🇶'),
  Country(code: 'GR', name: 'Greece', flagEmoji: '🇬🇷'),
  Country(code: 'GS', name: 'South Georgia and the South Sandwich Islands', flagEmoji: '🇬🇸'),
  Country(code: 'GT', name: 'Guatemala', flagEmoji: '🇬🇹'),
  Country(code: 'GU', name: 'Guam', flagEmoji: '🇬🇺'),
  Country(code: 'GW', name: 'Guinea-Bissau', flagEmoji: '🇬🇼'),
  Country(code: 'GY', name: 'Guyana', flagEmoji: '🇬🇾'),
  Country(code: 'HK', name: 'Hong Kong', flagEmoji: '🇭🇰'),
  Country(code: 'HM', name: 'Heard Island and McDonald Islands', flagEmoji: '🇭🇲'),
  Country(code: 'HN', name: 'Honduras', flagEmoji: '🇭🇳'),
  Country(code: 'HR', name: 'Croatia', flagEmoji: '🇭🇷'),
  Country(code: 'HT', name: 'Haiti', flagEmoji: '🇭🇹'),
  Country(code: 'HU', name: 'Hungary', flagEmoji: '🇭🇺'),
  Country(code: 'ID', name: 'Indonesia', flagEmoji: '🇮🇩'),
  Country(code: 'IE', name: 'Ireland', flagEmoji: '🇮🇪'),
  Country(code: 'IL', name: 'Israel', flagEmoji: '🇮🇱'),
  Country(code: 'IM', name: 'Isle of Man', flagEmoji: '🇮🇲'),
  Country(code: 'IN', name: 'India', flagEmoji: '🇮🇳'),
  Country(code: 'IO', name: 'British Indian Ocean Territory', flagEmoji: '🇮🇴'),
  Country(code: 'IQ', name: 'Iraq', flagEmoji: '🇮🇶'),
  Country(code: 'IR', name: 'Iran', flagEmoji: '🇮🇷'),
  Country(code: 'IS', name: 'Iceland', flagEmoji: '🇮🇸'),
  Country(code: 'IT', name: 'Italy', flagEmoji: '🇮🇹'),
  Country(code: 'JE', name: 'Jersey', flagEmoji: '🇯🇪'),
  Country(code: 'JM', name: 'Jamaica', flagEmoji: '🇯🇲'),
  Country(code: 'JO', name: 'Jordan', flagEmoji: '🇯🇴'),
  Country(code: 'KE', name: 'Kenya', flagEmoji: '🇰🇪'),
  Country(code: 'KG', name: 'Kyrgyzstan', flagEmoji: '🇰🇬'),
  Country(code: 'KH', name: 'Cambodia', flagEmoji: '🇰🇭'),
  Country(code: 'KI', name: 'Kiribati', flagEmoji: '🇰🇮'),
  Country(code: 'KM', name: 'Comoros', flagEmoji: '🇰🇲'),
  Country(code: 'KN', name: 'Saint Kitts and Nevis', flagEmoji: '🇰🇳'),
  Country(code: 'KP', name: 'North Korea', flagEmoji: '🇰🇵'),
  Country(code: 'KR', name: 'South Korea', flagEmoji: '🇰🇷'),
  Country(code: 'KW', name: 'Kuwait', flagEmoji: '🇰🇼'),
  Country(code: 'KY', name: 'Cayman Islands', flagEmoji: '🇰🇾'),
  Country(code: 'KZ', name: 'Kazakhstan', flagEmoji: '🇰🇿'),
  Country(code: 'LA', name: 'Laos', flagEmoji: '🇱🇦'),
  Country(code: 'LB', name: 'Lebanon', flagEmoji: '🇱🇧'),
  Country(code: 'LC', name: 'Saint Lucia', flagEmoji: '🇱🇨'),
  Country(code: 'LI', name: 'Liechtenstein', flagEmoji: '🇱🇮'),
  Country(code: 'LK', name: 'Sri Lanka', flagEmoji: '🇱🇰'),
  Country(code: 'LR', name: 'Liberia', flagEmoji: '🇱🇷'),
  Country(code: 'LS', name: 'Lesotho', flagEmoji: '🇱🇸'),
  Country(code: 'LT', name: 'Lithuania', flagEmoji: '🇱🇹'),
  Country(code: 'LU', name: 'Luxembourg', flagEmoji: '🇱🇺'),
  Country(code: 'LV', name: 'Latvia', flagEmoji: '🇱🇻'),
  Country(code: 'LY', name: 'Libya', flagEmoji: '🇱🇾'),
  Country(code: 'MA', name: 'Morocco', flagEmoji: '🇲🇦'),
  Country(code: 'MC', name: 'Monaco', flagEmoji: '🇲🇨'),
  Country(code: 'MD', name: 'Moldova', flagEmoji: '🇲🇩'),
  Country(code: 'ME', name: 'Montenegro', flagEmoji: '🇲🇪'),
  Country(code: 'MF', name: 'Saint Martin', flagEmoji: '🇲🇫'),
  Country(code: 'MG', name: 'Madagascar', flagEmoji: '🇲🇬'),
  Country(code: 'MH', name: 'Marshall Islands', flagEmoji: '🇲🇭'),
  Country(code: 'MK', name: 'North Macedonia', flagEmoji: '🇲🇰'),
  Country(code: 'ML', name: 'Mali', flagEmoji: '🇲🇱'),
  Country(code: 'MM', name: 'Myanmar', flagEmoji: '🇲🇲'),
  Country(code: 'MN', name: 'Mongolia', flagEmoji: '🇲🇳'),
  Country(code: 'MO', name: 'Macao', flagEmoji: '🇲🇴'),
  Country(code: 'MP', name: 'Northern Mariana Islands', flagEmoji: '🇲🇵'),
  Country(code: 'MQ', name: 'Martinique', flagEmoji: '🇲🇶'),
  Country(code: 'MR', name: 'Mauritania', flagEmoji: '🇲🇷'),
  Country(code: 'MS', name: 'Montserrat', flagEmoji: '🇲🇸'),
  Country(code: 'MT', name: 'Malta', flagEmoji: '🇲🇹'),
  Country(code: 'MU', name: 'Mauritius', flagEmoji: '🇲🇺'),
  Country(code: 'MV', name: 'Maldives', flagEmoji: '🇲🇻'),
  Country(code: 'MW', name: 'Malawi', flagEmoji: '🇲🇼'),
  Country(code: 'MX', name: 'Mexico', flagEmoji: '🇲🇽'),
  Country(code: 'MY', name: 'Malaysia', flagEmoji: '🇲🇾'),
  Country(code: 'MZ', name: 'Mozambique', flagEmoji: '🇲🇿'),
  Country(code: 'NA', name: 'Namibia', flagEmoji: '🇳🇦'),
  Country(code: 'NC', name: 'New Caledonia', flagEmoji: '🇳🇨'),
  Country(code: 'NE', name: 'Niger', flagEmoji: '🇳🇪'),
  Country(code: 'NF', name: 'Norfolk Island', flagEmoji: '🇳🇫'),
  Country(code: 'NG', name: 'Nigeria', flagEmoji: '🇳🇬'),
  Country(code: 'NI', name: 'Nicaragua', flagEmoji: '🇳🇮'),
  Country(code: 'NP', name: 'Nepal', flagEmoji: '🇳🇵'),
  Country(code: 'NR', name: 'Nauru', flagEmoji: '🇳🇷'),
  Country(code: 'NU', name: 'Niue', flagEmoji: '🇳🇺'),
  Country(code: 'NZ', name: 'New Zealand', flagEmoji: '🇳🇿'),
  Country(code: 'OM', name: 'Oman', flagEmoji: '🇴🇲'),
  Country(code: 'PA', name: 'Panama', flagEmoji: '🇵🇦'),
  Country(code: 'PE', name: 'Peru', flagEmoji: '🇵🇪'),
  Country(code: 'PF', name: 'French Polynesia', flagEmoji: '🇵🇫'),
  Country(code: 'PG', name: 'Papua New Guinea', flagEmoji: '🇵🇬'),
  Country(code: 'PH', name: 'Philippines', flagEmoji: '🇵🇭'),
  Country(code: 'PK', name: 'Pakistan', flagEmoji: '🇵🇰'),
  Country(code: 'PL', name: 'Poland', flagEmoji: '🇵🇱'),
  Country(code: 'PM', name: 'Saint Pierre and Miquelon', flagEmoji: '🇵🇲'),
  Country(code: 'PN', name: 'Pitcairn Islands', flagEmoji: '🇵🇳'),
  Country(code: 'PR', name: 'Puerto Rico', flagEmoji: '🇵🇷'),
  Country(code: 'PS', name: 'Palestine', flagEmoji: '🇵🇸'),
  Country(code: 'PT', name: 'Portugal', flagEmoji: '🇵🇹'),
  Country(code: 'PW', name: 'Palau', flagEmoji: '🇵🇼'),
  Country(code: 'PY', name: 'Paraguay', flagEmoji: '🇵🇾'),
  Country(code: 'QA', name: 'Qatar', flagEmoji: '🇶🇦'),
  Country(code: 'RE', name: 'Réunion', flagEmoji: '🇷🇪'),
  Country(code: 'RO', name: 'Romania', flagEmoji: '🇷🇴'),
  Country(code: 'RS', name: 'Serbia', flagEmoji: '🇷🇸'),
  Country(code: 'RU', name: 'Russia', flagEmoji: '🇷🇺'),
  Country(code: 'RW', name: 'Rwanda', flagEmoji: '🇷🇼'),
  Country(code: 'SA', name: 'Saudi Arabia', flagEmoji: '🇸🇦'),
  Country(code: 'SB', name: 'Solomon Islands', flagEmoji: '🇸🇧'),
  Country(code: 'SC', name: 'Seychelles', flagEmoji: '🇸🇨'),
  Country(code: 'SD', name: 'Sudan', flagEmoji: '🇸🇩'),
  Country(code: 'SG', name: 'Singapore', flagEmoji: '🇸🇬'),
  Country(code: 'SH', name: 'Saint Helena', flagEmoji: '🇸🇭'),
  Country(code: 'SI', name: 'Slovenia', flagEmoji: '🇸🇮'),
  Country(code: 'SJ', name: 'Svalbard and Jan Mayen', flagEmoji: '🇸🇯'),
  Country(code: 'SK', name: 'Slovakia', flagEmoji: '🇸🇰'),
  Country(code: 'SL', name: 'Sierra Leone', flagEmoji: '🇸🇱'),
  Country(code: 'SM', name: 'San Marino', flagEmoji: '🇸🇲'),
  Country(code: 'SN', name: 'Senegal', flagEmoji: '🇸🇳'),
  Country(code: 'SO', name: 'Somalia', flagEmoji: '🇸🇴'),
  Country(code: 'SR', name: 'Suriname', flagEmoji: '🇸🇷'),
  Country(code: 'SS', name: 'South Sudan', flagEmoji: '🇸🇸'),
  Country(code: 'ST', name: 'São Tomé and Príncipe', flagEmoji: '🇸🇹'),
  Country(code: 'SV', name: 'El Salvador', flagEmoji: '🇸🇻'),
  Country(code: 'SX', name: 'Sint Maarten', flagEmoji: '🇸🇽'),
  Country(code: 'SY', name: 'Syria', flagEmoji: '🇸🇾'),
  Country(code: 'SZ', name: 'Eswatini', flagEmoji: '🇸🇿'),
  Country(code: 'TC', name: 'Turks and Caicos Islands', flagEmoji: '🇹🇨'),
  Country(code: 'TD', name: 'Chad', flagEmoji: '🇹🇩'),
  Country(code: 'TF', name: 'French Southern Territories', flagEmoji: '🇹🇫'),
  Country(code: 'TG', name: 'Togo', flagEmoji: '🇹🇬'),
  Country(code: 'TH', name: 'Thailand', flagEmoji: '🇹🇭'),
  Country(code: 'TJ', name: 'Tajikistan', flagEmoji: '🇹🇯'),
  Country(code: 'TK', name: 'Tokelau', flagEmoji: '🇹🇰'),
  Country(code: 'TL', name: 'Timor-Leste', flagEmoji: '🇹🇱'),
  Country(code: 'TM', name: 'Turkmenistan', flagEmoji: '🇹🇲'),
  Country(code: 'TN', name: 'Tunisia', flagEmoji: '🇹🇳'),
  Country(code: 'TO', name: 'Tonga', flagEmoji: '🇹🇴'),
  Country(code: 'TR', name: 'Turkey', flagEmoji: '🇹🇷'),
  Country(code: 'TT', name: 'Trinidad and Tobago', flagEmoji: '🇹🇹'),
  Country(code: 'TV', name: 'Tuvalu', flagEmoji: '🇹🇻'),
  Country(code: 'TW', name: 'Taiwan', flagEmoji: '🇹🇼'),
  Country(code: 'TZ', name: 'Tanzania', flagEmoji: '🇹🇿'),
  Country(code: 'UA', name: 'Ukraine', flagEmoji: '🇺🇦'),
  Country(code: 'UG', name: 'Uganda', flagEmoji: '🇺🇬'),
  Country(code: 'UM', name: 'United States Minor Outlying Islands', flagEmoji: '🇺🇲'),
  Country(code: 'UY', name: 'Uruguay', flagEmoji: '🇺🇾'),
  Country(code: 'UZ', name: 'Uzbekistan', flagEmoji: '🇺🇿'),
  Country(code: 'VA', name: 'Vatican City', flagEmoji: '🇻🇦'),
  Country(code: 'VC', name: 'Saint Vincent and the Grenadines', flagEmoji: '🇻🇨'),
  Country(code: 'VE', name: 'Venezuela', flagEmoji: '🇻🇪'),
  Country(code: 'VG', name: 'British Virgin Islands', flagEmoji: '🇻🇬'),
  Country(code: 'VI', name: 'United States Virgin Islands', flagEmoji: '🇻🇮'),
  Country(code: 'VN', name: 'Vietnam', flagEmoji: '🇻🇳'),
  Country(code: 'VU', name: 'Vanuatu', flagEmoji: '🇻🇺'),
  Country(code: 'WF', name: 'Wallis and Futuna', flagEmoji: '🇼🇫'),
  Country(code: 'WS', name: 'Samoa', flagEmoji: '🇼🇸'),
  Country(code: 'YE', name: 'Yemen', flagEmoji: '🇾🇪'),
  Country(code: 'YT', name: 'Mayotte', flagEmoji: '🇾🇹'),
  Country(code: 'ZA', name: 'South Africa', flagEmoji: '🇿🇦'),
  Country(code: 'ZM', name: 'Zambia', flagEmoji: '🇿🇲'),
  Country(code: 'ZW', name: 'Zimbabwe', flagEmoji: '🇿🇼'),
];
