import 'package:turbo_disc_golf/models/data/course_data.dart';

const kTestCourses = [
  Course(
    id: 'test1',
    name: 'Sunny Pines',
    layouts: [
      CourseLayout(
        id: 'sunny18',
        name: '18-hole Main',
        holes: [
          CourseHole(holeNumber: 1, par: 3, feet: 325),
          CourseHole(holeNumber: 2, par: 4, feet: 420),
          CourseHole(holeNumber: 3, par: 3, feet: 280),
          CourseHole(holeNumber: 4, par: 3, feet: 350),
          CourseHole(holeNumber: 5, par: 4, feet: 500),
          CourseHole(holeNumber: 6, par: 3, feet: 280),
          CourseHole(holeNumber: 7, par: 4, feet: 470),
          CourseHole(holeNumber: 8, par: 3, feet: 290),
          CourseHole(holeNumber: 9, par: 3, feet: 360),
          CourseHole(holeNumber: 10, par: 4, feet: 440),
          CourseHole(holeNumber: 11, par: 3, feet: 315),
          CourseHole(holeNumber: 12, par: 3, feet: 293),
          CourseHole(holeNumber: 13, par: 4, feet: 463),
          CourseHole(holeNumber: 14, par: 3, feet: 287),
          CourseHole(holeNumber: 15, par: 4, feet: 410),
          CourseHole(holeNumber: 16, par: 3, feet: 300),
          CourseHole(holeNumber: 17, par: 3, feet: 282),
          CourseHole(holeNumber: 18, par: 5, feet: 650),
        ],
        isDefault: true,
      ),
    ],
    city: 'Springfield',
    state: 'OR',
    country: 'USA',
    description: 'Well-manicured park with gentle elevation changes.',
    uDiscId: 'udisc_123',
    pdgaId: 'pdga_789',
  ),
  Course(
    id: 'test2',
    name: 'Forest Glades',
    layouts: [
      CourseLayout(
        id: 'forest9',
        name: '9-hole Short',
        holes: [
          CourseHole(holeNumber: 1, par: 3, feet: 215),
          CourseHole(holeNumber: 2, par: 3, feet: 245),
          CourseHole(holeNumber: 3, par: 3, feet: 210),
          CourseHole(holeNumber: 4, par: 3, feet: 195),
          CourseHole(holeNumber: 5, par: 4, feet: 360),
          CourseHole(holeNumber: 6, par: 3, feet: 230),
          CourseHole(holeNumber: 7, par: 3, feet: 185),
          CourseHole(holeNumber: 8, par: 3, feet: 277),
          CourseHole(holeNumber: 9, par: 3, feet: 250),
        ],
        isDefault: true,
      ),
    ],
    city: 'Valley Creek',
    state: 'CA',
    country: 'USA',
    description: 'Wooded course, technical lines, ace runs.',
    uDiscId: 'udisc_212',
    pdgaId: 'pdga_312',
  ),
  Course(
    id: 'test3',
    name: 'Meadow Ridge',
    layouts: [
      CourseLayout(
        id: 'meadow18',
        name: 'Championship',
        holes: [
          CourseHole(holeNumber: 1, par: 4, feet: 530),
          CourseHole(holeNumber: 2, par: 3, feet: 285),
          CourseHole(holeNumber: 3, par: 3, feet: 315),
          CourseHole(holeNumber: 4, par: 4, feet: 470),
          CourseHole(holeNumber: 5, par: 3, feet: 325),
          CourseHole(holeNumber: 6, par: 4, feet: 450),
          CourseHole(holeNumber: 7, par: 3, feet: 275),
          CourseHole(holeNumber: 8, par: 3, feet: 310),
          CourseHole(holeNumber: 9, par: 3, feet: 258),
          CourseHole(holeNumber: 10, par: 4, feet: 490),
          CourseHole(holeNumber: 11, par: 4, feet: 515),
          CourseHole(holeNumber: 12, par: 3, feet: 308),
          CourseHole(holeNumber: 13, par: 3, feet: 240),
          CourseHole(holeNumber: 14, par: 3, feet: 273),
          CourseHole(holeNumber: 15, par: 4, feet: 505),
          CourseHole(holeNumber: 16, par: 3, feet: 333),
          CourseHole(holeNumber: 17, par: 3, feet: 286),
          CourseHole(holeNumber: 18, par: 5, feet: 700),
        ],
        isDefault: true,
      ),
    ],
    city: 'Mapleton',
    state: 'WA',
    country: 'USA',
    description: 'Flat terrain, open fairways, tricky OB.',
    uDiscId: 'udisc_555',
    pdgaId: 'pdga_678',
  ),
  Course(
    id: 'test4',
    name: 'Lakeside Park',
    layouts: [
      CourseLayout(
        id: 'lake6',
        name: '6-hole Family',
        holes: [
          CourseHole(holeNumber: 1, par: 3, feet: 170),
          CourseHole(holeNumber: 2, par: 3, feet: 140),
          CourseHole(holeNumber: 3, par: 3, feet: 115),
          CourseHole(holeNumber: 4, par: 3, feet: 180),
          CourseHole(holeNumber: 5, par: 3, feet: 160),
          CourseHole(holeNumber: 6, par: 3, feet: 154),
        ],
        isDefault: true,
      ),
    ],
    city: 'Greenville',
    state: 'IL',
    country: 'USA',
    description: 'Beginner friendly lakeside course for families.',
    uDiscId: 'udisc_910',
    pdgaId: 'pdga_820',
  ),
];
